version: '3'

volumes:
  img_converter_local_postgres_data: {}
  img_converter_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: img_converter_local_django
    container_name: img_converter_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: img_converter_production_postgres
    container_name: img_converter_local_postgres
    volumes:
      - img_converter_local_postgres_data:/var/lib/postgresql/data:Z
      - img_converter_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: img_converter_local_docs
    container_name: img_converter_local_docs
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./img_converter:/app/img_converter:z
    ports:
      - "9000:9000"
    command: /start-docs

  redis:
    image: redis:6
    container_name: img_converter_local_redis

  # celeryworker:
  #   <<: *django
  #   image: img_converter_local_celeryworker
  #   container_name: img_converter_local_celeryworker
  #   depends_on:
  #     - redis
  #     - postgres
  #   ports: []
  #   command: /start-celeryworker

  # celerybeat:
  #   <<: *django
  #   image: img_converter_local_celerybeat
  #   container_name: img_converter_local_celerybeat
  #   depends_on:
  #     - redis
  #     - postgres
  #   ports: []
  #   command: /start-celerybeat

  # flower:
  #   <<: *django
  #   image: img_converter_local_flower
  #   container_name: img_converter_local_flower
  #   ports:
  #     - 5555
  #   command: /start-flower
